"""Catálogo único de métricas para consultas e inspeção por tipo de sensor."""

import messages_pb2 as pb

# Nome no protocolo: (rótulo de apresentação, unidade, ícone).
METRICS = {
    "temperature": ("Temperatura ambiente", "C", "🌡️"),
    "humidity": ("Umidade relativa", "%", "💧"),
    "co2": ("CO₂", "ppm", "🌿"),
    "pm25": ("Partículas PM2.5", "ug/m3", "🌫️"),
    "pm10": ("Partículas PM10", "ug/m3", "💨"),
    "aqi": ("Índice de qualidade do ar simulado", "index", "🏭"),
    "wind_speed": ("Velocidade do vento", "m/s", "🌬️"),
    "wind_direction": ("Direção do vento", "deg", "🧭"),
    "atmospheric_pressure": ("Pressão atmosférica", "hPa", "🌦️"),
    "rainfall": ("Intensidade da chuva", "mm/h", "🌧️"),
    "noise_level": ("Ruído ambiente", "dB", "🔊"),
    "visibility": ("Visibilidade", "km", "👁️"),
    "uv_index": ("Índice UV", "index", "☀️"),
    "luminosity": ("Luminosidade do poste", "%", "💡"),
    "power_consumption": ("Potência elétrica", "W", "⚡"),
    "energy_consumption": ("Energia acumulada", "kWh", "🔋"),
    "voltage": ("Tensão elétrica", "V", "⚡"),
    "current": ("Corrente elétrica", "A", "⚡"),
    "led_temperature": ("Temperatura do LED", "C", "🌡️"),
    "ambient_light": ("Luz ambiente", "lux", "☀️"),
    "dimming_level": ("Intensidade da iluminação", "%", "💡"),
    "state": ("Fase do semáforo", "code", "🚦"),
    "queue_length": ("Fila veicular", "vehicles", "🚥"),
    "average_wait": ("Espera média no semáforo", "seconds", "⏱️"),
    "average_speed": ("Velocidade média dos veículos", "km/h", "🚗"),
    "road_occupancy": ("Ocupação da via", "%", "🛣️"),
    "cycle_duration": ("Duração do ciclo semafórico", "seconds", "🔄"),
    "pedestrians_count": ("Fluxo de pedestres", "pedestrians/min", "🚶"),
    "green_remaining": ("Tempo restante da fase verde", "seconds", "🚦"),
    "vehicles_count": ("Fluxo de veículos", "veh/min", "🚗"),
    "infractions": ("Infrações detectadas", "count", "📸"),
    "accidents": ("Acidentes detectados", "count", "🚨"),
    "detection_confidence": ("Confiança da detecção", "%", "🎯"),
    "heavy_vehicles_count": ("Fluxo de veículos pesados", "veh/min", "🚛"),
    "total_spaces": ("Total de vagas", "spaces", "🅿️"),
    "occupied_spaces": ("Vagas ocupadas", "spaces", "🚙"),
    "available_spaces": ("Vagas disponíveis", "spaces", "✅"),
    "occupancy_rate": ("Ocupação do estacionamento", "%", "📊"),
    "vehicle_turnover": ("Rotatividade de veículos", "vehicles/min", "🔄"),
    "arrivals": ("Chegadas no intervalo", "vehicles", "➡️"),
    "departures": ("Saídas no intervalo", "vehicles", "⬅️"),
    "parking_wait_time": ("Espera no estacionamento", "min", "⏱️"),
    "hourly_revenue": ("Receita estimada por hora", "BRL/h", "💰"),
    "ev_charging_vehicles": ("Veículos elétricos em recarga", "vehicles", "🔌"),
    "ev_charging_power": ("Potência da recarga elétrica", "kW", "⚡"),
    "water_level": ("Nível da água", "%", "💧"),
    "water_flow": ("Vazão da água", "L/min", "🚰"),
    "water_pressure": ("Pressão da água", "bar", "🚰"),
    "water_ph": ("pH da água", "pH", "🧪"),
    "water_turbidity": ("Turbidez da água", "NTU", "🧪"),
    "water_temperature": ("Temperatura da água", "°C", "🌡️"),
    "conductivity": ("Condutividade da água", "uS/cm", "⚡"),
    "leak_rate": ("Vazamento estimado", "L/min", "💦"),
    "waste_fill_level": ("Ocupação da lixeira", "%", "🗑️"),
    "waste_weight": ("Peso dos resíduos", "kg", "⚖️"),
    "bin_temperature": ("Temperatura da lixeira", "C", "🌡️"),
    "bin_humidity": ("Umidade da lixeira", "%", "💧"),
    "battery_level": ("Carga da bateria", "%", "🔋"),
    "signal_strength": ("Intensidade do sinal", "dBm", "📶"),
    "collection_count": ("Coletas realizadas", "count", "🚛"),
    "tilt_angle": ("Inclinação da lixeira", "deg", "📐"),
    "fire_risk": ("Indicador simulado de aquecimento", "%", "🔥"),
}

ENVIRONMENT_METRICS = list(METRICS)[:13]
DEVICE_METRICS_MAP = {
    pb.DEVICE_TYPE_WEATHER_STATION: ENVIRONMENT_METRICS,
    pb.DEVICE_TYPE_AIR_QUALITY: ENVIRONMENT_METRICS,
    pb.DEVICE_TYPE_LAMP_POST: ["luminosity", "power_consumption", "energy_consumption", "voltage", "current", "led_temperature", "ambient_light", "dimming_level"],
    pb.DEVICE_TYPE_TRAFFIC_LIGHT: ["state", "queue_length", "average_wait", "average_speed", "road_occupancy", "cycle_duration", "pedestrians_count", "green_remaining"],
    pb.DEVICE_TYPE_CAMERA: ["vehicles_count", "infractions", "average_speed", "road_occupancy", "accidents", "pedestrians_count", "detection_confidence", "heavy_vehicles_count"],
    pb.DEVICE_TYPE_PARKING_SENSOR: ["total_spaces", "occupied_spaces", "available_spaces", "occupancy_rate", "vehicle_turnover", "arrivals", "departures", "parking_wait_time", "hourly_revenue", "ev_charging_vehicles", "ev_charging_power"],
    pb.DEVICE_TYPE_WATER_SENSOR: ["water_level", "water_flow", "water_pressure", "water_ph", "water_turbidity", "water_temperature", "conductivity", "leak_rate"],
    pb.DEVICE_TYPE_WASTE_SENSOR: ["waste_fill_level", "waste_weight", "bin_temperature", "bin_humidity", "battery_level", "signal_strength", "collection_count", "tilt_angle", "fire_risk"],
}
METRIC_ICONS = {key: definition[2] for key, definition in METRICS.items()}
METRIC_UNITS = {key: definition[1] for key, definition in METRICS.items()}
METRIC_OPTIONS = [(f"{icon} {label} ({unit})", key) for key, (label, unit, icon) in METRICS.items()]
