[package]
name = "aggregator-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
redis = { version = "0.25", features = ["tokio-comp"] }
prost = "0.12"
prost-types = "0.12"
lazy_static = "1.4.0"

[build-dependencies]
prost-build = "0.12"

rand = "0.8.5"
aes-gcm = "0.10.3"
